version: "3.8"

services:
  reverse-proxy:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 80:80
    depends_on:
      - db
    volumes:
      - ./packages/config/nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'cmsdb'
      MYSQL_USER: 'cmsdbadmin'
      MYSQL_PASSWORD: 'cmsdbadmin23'
      MYSQL_ROOT_PASSWORD: '@_cmsdbadmin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-cms-db:/var/lib/mysql

volumes:
  my-cms-db:
